INSERT INTO products (name, description, price, category_id, image, status, discount_id)
VALUES
('Sher Atta Desi Style 20 lb', 'Premium desi-style wheat flour for soft rotis and parathas.', 17.99, 1, 'placeholder.png', 'active', 1),
('Ocean Pearl Rice 10 lb', 'High-quality long grain rice, perfect for daily cooking.', 13.99, 2, 'placeholder.png', 'active', 2),
('Dewan Basmati Rice 10 lb', 'Aromatic basmati rice ideal for biryani and pulao.', 15.99, 2, 'placeholder.png', 'active', 3),
('Minar Classic Rice 10 lb', 'Classic rice with excellent texture and aroma.', 14.99, 2, 'placeholder.png', 'active', 4),
('Guard Basmati Rice 10 lb', 'Authentic basmati rice with long grains.', 14.99, 2, 'placeholder.png', 'active', 5),
('Handi Extreme Rice', 'Premium quality rice with enhanced flavor.', 11.99, 2, 'placeholder.png', 'active', 6),
('Shan Paste 700 gm', 'Ready-to-use cooking pastes for desi dishes.', 5.49, 3, 'placeholder.png', 'active', 7),
('Handi Paste 750 gm', 'Cooking pastes packed with traditional spices.', 4.99, 3, 'placeholder.png', 'active', 8),
('Handi Fried Onion 400 gm', 'Crispy fried onions for garnishing biryani and curries.', 2.99, 3, 'placeholder.png', 'active', 9),
('PK Sunflower Oil 3 Litre', 'Healthy sunflower oil for everyday use.', 8.99, 4, 'placeholder.png', 'active', 10),
('Patanjali Mustard Oil 1 Litre', 'Strong, aromatic mustard oil.', 6.99, 4, 'placeholder.png', 'active', 11),
('Tez Mustard Oil 4.75 Litre', 'Large pack of mustard oil for bulk use.', 27.99, 4, 'placeholder.png', 'active', 12),
('Patanjali Mustard Oil 5 Litre', 'Natural mustard oil in a 5-litre pack.', 24.99, 4, 'placeholder.png', 'active', 13),
('Nanak Desi Ghee 1.6 kg', 'Traditional clarified butter for cooking.', 28.99, 3, 'placeholder.png', 'active', 14),
('Sher Besan 4 lb', 'Gram flour used in a variety of desi recipes.', 6.99, 3, 'placeholder.png', 'active', 15),
('Nestle Everyday Powder 850 gm', 'Creamer powder for tea and coffee.', 16.99, 3, 'placeholder.png', 'active', 16),
('Tapal Danedar Tea Pouch 900 gm', 'Strong, flavorful tea blend.', 12.99, 5, 'placeholder.png', 'active', 17),
('Tetley Tea 300 gm', 'Popular black tea for daily use.', 16.99, 5, 'placeholder.png', 'active', 18),
('Tapal Danedar Tea 220 Bags', 'Convenient tea bags with rich taste.', 10.99, 5, 'placeholder.png', 'active', 19),
('Tapal Green Tea 30 Bags', 'Green tea bags for a healthy lifestyle.', 4.99, 5, 'placeholder.png', 'active', 20),
('Red Label Tea 900 gm', 'Full-bodied Indian tea.', 12.99, 5, 'placeholder.png', 'active', 21),
('Nestle Dairy Cream 200 ml', 'Rich dairy cream for desserts and tea.', 4.99, 3, 'placeholder.png', 'active', 22),
('Lipton Danedar Tea Jar 475 gm', 'Danedar blend for strong flavor.', 8.99, 5, 'placeholder.png', 'active', 23),
('Barbican Drink 6 Pack', 'Non-alcoholic malt drink.', 10.99, 3, 'placeholder.png', 'active', 24),
('Shezan Juice 6 x 250 ml', 'Assorted fruit juices in glass bottles.', 12.99, 3, 'placeholder.png', 'active', 25),
('Shezan Juice 36 x 250 ml', 'Bulk fruit juice pack.', 29.99, 3, 'placeholder.png', 'active', 26),
('National Pickle 1 kg', 'Mixed vegetable pickle with spices.', 6.99, 3, 'placeholder.png', 'active', 27),
('Shezan Cordia Mix 1 kg', 'Traditional tangy Cordia fruit pickle.', 4.99, 3, 'placeholder.png', 'active', 28),
('Shezan Lime Chilli Pickle 1 kg', 'Spicy lime and chilli pickle.', 4.99, 3, 'placeholder.png', 'active', 29),
('GV Khudri Dates 1 kg', 'Sweet, chewy Khudri dates.', 9.99, 3, 'placeholder.png', 'active', 30),
('GV Medjoul Dates 1 kg', 'Premium Medjoul dates.', 17.99, 3, 'placeholder.png', 'active', 31),
('Dawn Paratha Family Pack 30 Pcs', 'Ready-to-cook layered parathas.', 9.99, 3, 'placeholder.png', 'active', 32),
('Brar’s Desi Ghee 1.6 kg', 'High quality desi ghee.', 29.99, 3, 'placeholder.png', 'active', 33),
('Shezan Sarson Ka Saag 840 gm', 'Ready-to-eat traditional mustard greens.', 4.99, 3, 'placeholder.png', 'active', 34),
('Mitchell’s Sarson Ka Saag 800 gm', 'Authentic saag with home-style flavor.', 4.99, 3, 'placeholder.png', 'active', 35),
('Fresh Chicken Leg Clean', 'Clean chicken legs for cooking.', 3.99, 3, 'placeholder.png', 'active', 36),
('Fresh Chicken Thigh Clean', 'Cleaned chicken thighs.', 5.99, 3, 'placeholder.png', 'active', 37),
('Fresh Goat Leg', 'Halal goat leg, fresh cut.', 13.99, 3, 'placeholder.png', 'active', 38),
('Fresh Goat Shoulder', 'Halal goat shoulder meat.', 11.99, 3, 'placeholder.png', 'active', 39),
('Fresh Beef Eye of Round', 'Lean cut of beef.', 9.99, 3, 'placeholder.png', 'active', 40),
('Fresh Beef Veal with Bone', 'Veal with bone, perfect for stews.', 7.99, 3, 'placeholder.png', 'active', 41),
('Marhaba Ispaghol Husk 95 gm', 'Fiber-rich psyllium husk.', 7.99, 3, 'placeholder.png', 'active', 42),
('Potato White 10 lb', 'White potatoes for everyday cooking.', 4.99, 3, 'placeholder.png', 'active', 43),
('Onion Yellow 10 lb', 'Yellow onions for all kinds of dishes.', 4.99, 3, 'placeholder.png', 'active', 44);